function [enables,prompts] = block(a,object,values,enables,prompts)

type   = str2num(values{1});
idx1 = [4 5 6 7 8];
idx2 = [7 8 11];

switch type
 case 1
  prompts(idx1) = {'Regulator Gain m0 [p.u./p.u.]'; ....
             'First Regulator Pole T1 [s]'; ...
             'First Regulator Zero T2 [s]'; ...
             'Second Regulator Pole T3 [s]'; ...
             'Second Regulator Zero T4 [s]'};
  enables(idx2) = {'on'; 'on'; 'on'};
 case 2
  prompts(idx1) = {'Amplifier Gain Ka [p.u./p.u.]'; ...
             'Amplifier Time Constant Ta [s]'; ...
             'Stabilizer Gain Kf [p.u./p.u.]'; ...
             'Stabilizer Time Tf [s]'; ...
             'Integral deviation Ke [p.u./p.u.]'};
  enables(idx2) = {'on'; 'on'; 'on'};
 case 3
  prompts(idx1) = {'Regulator Gain [p.u./p.u.]'; ...
             'Regulator Pole T2 [s]'; ...
             'Regulator Zero T1 [s]'; ...
             'Second Regulator Pole T3 [s]'; ...
             'Allow signal V/V0 [0 for disabling signal]'};
  enables(idx2) = {'off'; 'on'; 'off'};
end
  
